version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile_1
    container_name: dirigible_service1
    networks:
      - dirigible_network
    ports:
      - "8081:8080"  # Map host port 8081 to container port 8080
    environment:
      - SERVICE_NAME=service1  # Name of your service as registered in Keycloak

  service2:
    build:
      context: .
      dockerfile: Dockerfile_2
    container_name: dirigible_service2
    networks:
      - dirigible_network
    ports:
      - "8082:8080"  # Map host port 8082 to container port 8080
    environment:
      - SERVICE_NAME=service2  # Name of your service as registered in Keycloak

  service3:
    build:
      context: .
      dockerfile: Dockerfile_3
    container_name: dirigible_service3
    networks:
      - dirigible_network
    ports:
      - "8083:8080"  # Map host port 8083 to container port 8080
    environment:
      - SERVICE_NAME=service3  # Name of your service as registered in Keycloak
      - DIRIGIBLE_HOME_URL=/services/web/alien_service/gen/index.html

  db1:
    image: mariadb:10.5
    container_name: dirigible_db1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dirigibledb
      - CLUSTER_NAME=dirigible_cluster
      - XTRABACKUP_PASSWORD=xtrabackup
    volumes:
      - db1_data:/var/lib/mysql
    networks:
      - dirigible_network
    ports:
      - "3306:3306"
    command: --wsrep-new-cluster

  db2:
    image: mariadb:10.5
    container_name: dirigible_db2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dirigibledb
      - CLUSTER_NAME=dirigible_cluster
      - XTRABACKUP_PASSWORD=xtrabackup
    volumes:
      - db2_data:/var/lib/mysql
    networks:
      - dirigible_network
    ports:
      - "3307:3306"
    depends_on:
      - db1
    command: --wsrep_cluster_address=gcomm://dirigible_db1

  haproxy:
    image: haproxy:latest
    container_name: dirigible_haproxy
    depends_on:
      - db1
      - db2
    networks:
      - dirigible_network
    ports:
      - "3308:3306"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

networks:
  dirigible_network:
    driver: bridge

volumes:
  db1_data:
  db2_data:
