version: '3.8'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile_1
    container_name: service1
    networks:
      - dirigible_network
    ports:
      - "8081:8080"
    depends_on:
      - keycloak
    environment:
      - SERVICE_NAME=service1

  service2:
    build:
      context: .
      dockerfile: Dockerfile_2
    container_name: service2
    networks:
      - dirigible_network
    ports:
      - "8082:8080"
    depends_on:
      - keycloak
    environment:
      - SERVICE_NAME=service2

  service3:
    build:
      context: .
      dockerfile: Dockerfile_3
    container_name: service3
    networks:
      - dirigible_network
    ports:
      - "8083:8080"
    depends_on:
      - keycloak
    environment:
      - SERVICE_NAME=service3
      - DIRIGIBLE_HOME_URL=/services/web/alien_service/gen/index.html

  db1:
    image: mariadb:10.5
    container_name: db1
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dirigibledb
      - CLUSTER_NAME=dirigible_cluster
      - XTRABACKUP_PASSWORD=xtrabackup
    volumes:
      - db1_data:/var/lib/mysql
    networks:
      - dirigible_network
    ports:
      - "3306:3306"
    command: --wsrep-new-cluster

  db2:
    image: mariadb:10.5
    container_name: db2
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dirigibledb
      - CLUSTER_NAME=dirigible_cluster
      - XTRABACKUP_PASSWORD=xtrabackup
    volumes:
      - db2_data:/var/lib/mysql
    networks:
      - dirigible_network
    ports:
      - "3307:3306"
    depends_on:
      - db1
    command: --wsrep_cluster_address=gcomm://dirigible_db1

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    depends_on:
      - db1
      - db2
    networks:
      - dirigible_network
    ports:
      - "3308:3306"
      - "8080:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - DB_VENDOR=mariadb
      - DB_ADDR=haproxy
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-config.json
    networks:
      - dirigible_network
    ports:
      - "2000:8080"
    depends_on:
      - haproxy
    volumes:
      - ./keycloak/realm-config.json:/tmp/realm-config.json:ro
    command:
      - "start"
      - "--optimized"
      - "--http-enabled=true"
      - "--http-port=8080"
      - "--hostname-strict=false"
      - "-Dquarkus.transaction-manager.enable-recovery=true"
      - "-Djboss.socket.binding.port-offset=1000"
      - "-Dquarkus.http.host=0.0.0.0"
      - "-Dquarkus.http.port=8080"
      - "-Dquarkus.http.host-verification=false"

networks:
  dirigible_network:
    driver: bridge

volumes:
  db1_data:
  db2_data:
